schemaVersion: 2.0.0

metadataTest:
  # Image has expected default metadata
  env:
    - key: GOPATH
      value: /go
  exposedPorts: []
  volumes: []
  entrypoint: []

fileExistenceTests:
  # Main binary exists
  - name: Check existance of go file in the path
    # The following will pass
    # path: /usr/local/go/bin/go
    # The following will fail
    path: /usr/local/go/bin/go123
    shouldExist: true
    permissions: "-rwxr-xr-x"

commandTests:
  # Main binary can print its version
  - name: Test the correct version number of go
    command: go
    args: ["version"]
    # the image version number is 1.19.1. The following will fail
    expectedOutput: ["go version go1.14.6"]
    # The following will pass
    # expectedOutput: ["go version go1.19.1"]
    # Since a new container is created, we have to exit from the container. We are using exit code to exit
    exitCode: 0
    
  # Can compile a valid "hello world"
  - name: Test if hello world is displayed
    setup: [["wget", "https://raw.githubusercontent.com/go-training/helloworld/master/main.go"]]
    command: go
    args: ["run", "main.go"]
    # The following fail
    expectedOutput: ["Helloo World!!"]
    # The following will pass
    # expectedOutput: ["Hello World!!"]
    exitCode: 0
    teardown: [["rm", "main.go"]]
